In [22]:
import pandas as pd
df1 = pd.read_csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv")
df1["Date"] = df1['Province/State']
df1['Date'].fillna(df1['Country/Region'], inplace=True)
df1=df1.drop(['Province/State','Country/Region','Lat','Long'], axis=1)
df1.set_index('Date', inplace=True)
df1 = df1.transpose()
df1 = df1[['India', 'Germany', 'United Arab Emirates', 'Italy', 'Spain', 'Ireland', 'Qatar', 'Saudi Arabia', 'Washington', 'New York', 'California', 'Hubei', 'Iran', 'France', 'Shanghai', 'Korea, South', 'Taiwan*']]
df1.to_csv('covid19-data.csv')

In [24]:
df1

Date,India,Germany,United Arab Emirates,Italy,Spain,Ireland,Qatar,Saudi Arabia,Washington,New York,California,Hubei,Iran,France,Shanghai,"Korea, South",Taiwan*
1/22/20,0,0,0,0,0,0,0,0,0,0,0,444,0,0,9,1,1
1/23/20,0,0,0,0,0,0,0,0,0,0,0,444,0,0,16,1,1
1/24/20,0,0,0,0,0,0,0,0,0,0,0,549,0,2,20,2,3
1/25/20,0,0,0,0,0,0,0,0,0,0,0,761,0,3,33,2,3
1/26/20,0,0,0,0,0,0,0,0,0,0,0,1058,0,3,40,3,4
1/27/20,0,1,0,0,0,0,0,0,0,0,0,1423,0,3,53,4,5
1/28/20,0,4,0,0,0,0,0,0,0,0,0,3554,0,4,66,4,8
1/29/20,0,4,4,0,0,0,0,0,0,0,0,3554,0,5,96,4,8
1/30/20,1,4,4,0,0,0,0,0,0,0,0,4903,0,5,112,4,9
1/31/20,1,5,4,2,0,0,0,0,0,0,0,5806,0,5,135,11,10
2/1/20,1,8,4,2,1,0,0,0,0,0,0,7153,0,6,169,12,10
2/2/20,2,10,5,2,1,0,0,0,0,0,0,11177,0,6,182,15,10
2/3/20,3,12,5,2,1,0,0,0,0,0,0,13522,0,6,203,15,10
2/4/20,3,12,5,2,1,0,0,0,0,0,0,16678,0,6,219,16,11
2/5/20,3,12,5,2,1,0,0,0,0,0,0,19665,0,6,243,19,11
2/6/20,3,12,5,2,1,0,0,0,0,0,0,22112,0,6,257,23,16
2/7/20,3,13,5,3,1,0,0,0,0,0,0,24953,0,6,277,24,16
2/8/20,3,13,7,3,1,0,0,0,0,0,0,27100,0,11,286,24,17
2/9/20,3,14,7,3,2,0,0,0,0,0,0,29631,0,11,293,25,18
2/10/20,3,14,8,3,2,0,0,0,0,0,0,31728,0,11,299,27,18
2/11/20,3,16,8,3,2,0,0,0,0,0,0,33366,0,11,303,28,18
2/12/20,3,16,8,3,2,0,0,0,0,0,0,33366,0,11,311,28,18
2/13/20,3,16,8,3,2,0,0,0,0,0,0,48206,0,11,315,28,18
2/14/20,3,16,8,3,2,0,0,0,0,0,0,54406,0,11,318,28,18
2/15/20,3,16,8,3,2,0,0,0,0,0,0,56249,0,12,326,28,18
2/16/20,3,16,9,3,2,0,0,0,0,0,0,58182,0,12,328,29,20
2/17/20,3,16,9,3,2,0,0,0,0,0,0,59989,0,12,333,30,22
2/18/20,3,16,9,3,2,0,0,0,0,0,0,61682,0,12,333,31,22
2/19/20,3,16,9,3,2,0,0,0,0,0,0,62031,2,12,333,31,23
2/20/20,3,16,9,3,2,0,0,0,0,0,0,62442,5,12,334,104,24
2/21/20,3,16,9,20,2,0,0,0,0,0,0,62662,18,12,334,204,26
2/22/20,3,16,13,62,2,0,0,0,0,0,0,64084,28,12,335,433,26
2/23/20,3,16,13,155,2,0,0,0,0,0,0,64084,43,12,335,602,28
2/24/20,3,16,13,229,2,0,0,0,0,0,0,64287,61,12,335,833,30
2/25/20,3,17,13,322,6,0,0,0,0,0,0,64786,95,14,336,977,31
2/26/20,3,27,13,453,13,0,0,0,0,0,0,65187,139,18,337,1261,32
2/27/20,3,46,13,655,15,0,0,0,0,0,0,65596,245,38,337,1766,32
2/28/20,3,48,19,888,32,0,0,0,0,0,0,65914,388,57,337,2337,34
2/29/20,3,79,21,1128,45,1,1,0,0,0,0,66337,593,100,337,3150,39
3/1/20,3,130,21,1694,84,1,3,0,0,0,0,66907,978,130,337,3736,40
3/2/20,5,159,21,2036,120,1,3,1,0,0,0,67103,1501,191,337,4335,41
3/3/20,5,196,27,2502,165,2,7,1,0,0,0,67217,2336,204,338,5186,42
3/4/20,28,262,27,3089,222,6,8,1,0,0,0,67332,2922,285,338,5621,42
3/5/20,30,482,29,3858,259,6,8,5,0,0,0,67466,3513,377,339,6088,44
3/6/20,31,670,29,4636,400,18,8,5,0,0,0,67592,4747,653,342,6593,45
3/7/20,34,799,45,5883,500,18,8,5,0,0,0,67666,5823,949,342,7041,45
3/8/20,39,1040,45,7375,673,19,15,11,0,0,0,67707,6566,1126,342,7314,45
3/9/20,43,1176,45,9172,1073,21,18,15,0,0,0,67743,7161,1209,342,7478,45
3/10/20,56,1457,74,10149,1695,34,24,20,267,173,144,67760,8042,1784,344,7513,47
3/11/20,62,1908,74,12462,2277,43,262,21,366,220,177,67773,9000,2281,344,7755,48
3/12/20,73,2078,85,12462,2277,43,262,45,442,328,221,67781,10075,2281,344,7869,49
3/13/20,82,3675,85,17660,5232,90,320,86,568,421,282,67786,11364,3661,346,7979,50
3/14/20,102,4585,85,21157,6391,129,337,103,572,525,340,67790,12729,4469,353,8086,53
3/15/20,113,5795,98,24747,7798,129,401,103,643,732,426,67794,13938,4499,353,8162,59
3/16/20,119,7272,98,27980,9942,169,439,118,904,967,557,67798,14991,6633,355,8236,67